name: ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.1 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    stacked: ^3.4.1+1
    http: ^1.2.0
    stacked_services: ^1.3.0
    stacked_core: ^1.2.3

    flutter_secure_storage: ^5.0.2
    shared_preferences: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

    stacked_generator: ^0.7.8
    build_runner: ^2.4.7

flutter:
    uses-material-design: true
