# Generated by Django 4.2.6 on 2024-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacturing_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
